baseURL = 'https://raziman.online/'
languageCode = 'en-us'
title = "journal of issadarkthing"
theme = "terra"
pygmentsUseClasses = true
pygmentsCodeFences = true
googleAnalytics = "G-17S8480P0Z"
enableRobotsTXT = true
disqusShortname = "issadarkthing-com"

[params]
  description = "blog that discusses about open source software"
  copyright = "Copyright Â© 2023 issadarkthing"
  dark = "on"
  highlight = true

[[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "posts"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "tags"
  name = "tags"
  title = "tags"
  url = "/tags/"
  weight = 2

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "about"
  url = "/about/"
  weight = 3


[permalinks]
  posts = "/:title/"
